<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>Binaries\</OutputPath>
    <IntermediateOutputPath>Intermediates\Debug\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>Binaries\</OutputPath>
    <IntermediateOutputPath>Intermediates\Release\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Dist|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
    <OutputPath>Binaries\</OutputPath>
    <IntermediateOutputPath>Intermediates\Dist\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Reference Include="Hazel-ScriptCore">
      <HintPath>..\..\..\Resources\Scripts\Hazel-ScriptCore.dll</HintPath>
    </Reference>
    <Reference Include="Coral.Managed">
      <HintPath>..\..\..\DotNet\Coral.Managed.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Reference Include="Hazel-ScriptCore">
      <HintPath>..\..\..\Resources\Scripts\Hazel-ScriptCore.dll</HintPath>
    </Reference>
    <Reference Include="Coral.Managed">
      <HintPath>..\..\..\DotNet\Coral.Managed.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Dist|AnyCPU' ">
    <Reference Include="Hazel-ScriptCore">
      <HintPath>..\..\..\Resources\Scripts\Hazel-ScriptCore.dll</HintPath>
    </Reference>
    <Reference Include="Coral.Managed">
      <HintPath>..\..\..\DotNet\Coral.Managed.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Source\AudioController.cs" />
    <Compile Include="Source\AudioDemo.cs" />
    <Compile Include="Source\BasicController.cs" />
    <Compile Include="Source\FPSPlayer.cs" />
    <Compile Include="Source\FirstPersonController.cs" />
    <Compile Include="Source\Flocking\Boid.cs" />
    <Compile Include="Source\Flocking\BoidHelper.cs" />
    <Compile Include="Source\Flocking\BoidManager.cs" />
    <Compile Include="Source\Flocking\BoidSettings.cs" />
    <Compile Include="Source\MapGenerator.cs" />
    <Compile Include="Source\Noise.cs" />
    <Compile Include="Source\PhysicsCubeSpawner.cs" />
    <Compile Include="Source\PhysicsTest.cs" />
    <Compile Include="Source\PlayerController2D.cs" />
    <Compile Include="Source\PlayerCube.cs" />
    <Compile Include="Source\PlayerSphere.cs" />
    <Compile Include="Source\Projectile.cs" />
    <Compile Include="Source\RandomColor.cs" />
    <Compile Include="Source\SandboxUtility.cs" />
    <Compile Include="Source\ScriptSpawner.cs" />
    <Compile Include="Source\TeleportTest.cs" />
    <Compile Include="Source\Testing.cs" />
    <Compile Include="Source\Tests\CSharpTest.cs" />
    <Compile Include="Source\Tests\CollisionCallbackTest.cs" />
    <Compile Include="Source\Tests\DOF-Test.cs" />
    <Compile Include="Source\Tests\EntityTest.cs" />
    <Compile Include="Source\Tests\ExceptionTest.cs" />
    <Compile Include="Source\ThirdPerson.cs" />
  </ItemGroup>
</Project>